local test = peripheral.wrap("back")
test.setBackgroundColor(colors.black)
test.setTextColor(colors.white)
test.clear()
test.setCursorPos(1, 1)
test.setTextScale(1)
test.write("test")
test.setTextScale(2)
test.write("test2")
